SistemaGestionGimnasio/Controllers/MembresiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaGestionGimnasio.Models;

namespace SistemaGestionGimnasio.Controllers
{
    public class MembresiaController : Controller
    {
        private readonly Gym_BDContext _context;

        public MembresiaController(Gym_BDContext context)
        {
            _context = context;
        }

        // GET: Membresia
        public async Task<IActionResult> Index(string filtroCedula, DateTime? filtroFechaInicio, DateTime? filtroFechaFin)
        {
            if (HttpContext.Session.GetString("Usuario") == "" || HttpContext.Session.GetString("Usuario") == null)
            {
                return RedirectToAction("Index", "Usuario");
            }
            ViewBag.Usuario = HttpContext.Session.GetString("Usuario");
            ViewBag.Tipo = HttpContext.Session.GetInt32("Tipo");
            // Obtén todas las membresías incluyendo la información del cliente.
            var membresiasQuery = _context.Membresia.Include(m => m.ClienteCedulaNavigation).AsQueryable();

            // Aplica los filtros según sea necesario.
            if (!string.IsNullOrEmpty(filtroCedula))
            {
                membresiasQuery = membresiasQuery
    .Where(m => m.ClienteCedulaNavigation.ClienteCedula.StartsWith(filtroCedula) && !m.ClienteCedulaNavigation.Eliminado);
            }

            if (filtroFechaInicio.HasValue)
            {
                membresiasQuery = membresiasQuery.Where(m => m.FechaInicio >= filtroFechaInicio);
            }

            if (filtroFechaFin.HasValue)
            {
                membresiasQuery = membresiasQuery.Where(m => m.FechaVencimiento <= filtroFechaFin);
            }

            // Ejecuta la consulta y devuelve los resultados a la vista.
            var resultadosFiltrados = await membresiasQuery.ToListAsync();

            return View(resultadosFiltrados);
        }


        // GET: Membresia/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Membresia == null)
            {
                return NotFound();
            }

            var membresium = await _context.Membresia
                .Include(m => m.ClienteCedulaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (membresium == null)
            {
                return NotFound();
            }

            return View(membresium);
        }

        // GET: Membresia/Create
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("Usuario") == "" || HttpContext.Session.GetString("Usuario") == null)
            {
                return RedirectToAction("Index", "Usuario");
            }
            ViewBag.Usuario = HttpContext.Session.GetString("Usuario");
            ViewBag.Tipo = HttpContext.Session.GetInt32("Tipo");
            ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "ClienteCedula", "ClienteCedula");
            return View();
        }

        // POST: Membresia/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FechaInicio,FechaVencimiento,TipoMembresia,Precio,ClienteCedula")] Membresium membresium)
        {
            if (HttpContext.Session.GetString("Usuario") == "" || HttpContext.Session.GetString("Usuario") == null)
            {
                return RedirectToAction("Index", "Usuario");
            }
            ViewBag.Usuario = HttpContext.Session.GetString("Usuario");
            ViewBag.Tipo = HttpContext.Session.GetInt32("Tipo");
            if (ModelState.IsValid)
            {
                _context.Add(membresium);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "ClienteCedula", "ClienteCedula", membresium.ClienteCedula);
            return View(membresium);
        }

        // GET: Membresia/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (HttpContext.Session.GetString("Usuario") == "" || HttpContext.Session.GetString("Usuario") == null)
            {
                return RedirectToAction("Index", "Usuario");
            }
            ViewBag.Usuario = HttpContext.Session.GetString("Usuario");
            ViewBag.Tipo = HttpContext.Session.GetInt32("Tipo");
            if (id == null || _context.Membresia == null)
            {
                return NotFound();
            }

            var membresium = await _context.Membresia.FindAsync(id);
            if (membresium == null)
            {
                return NotFound();
            }
            ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "ClienteCedula", "ClienteCedula", membresium.ClienteCedula);
            return View(membresium);
        }

        // POST: Membresia/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FechaInicio,FechaVencimiento,TipoMembresia,Precio,ClienteCedula")] Membresium membresium)
        {
            if (HttpContext.Session.GetString("Usuario") == "" || HttpContext.Session.GetString("Usuario") == null)
            {
                return RedirectToAction("Index", "Usuario");
            }
            ViewBag.Usuario = HttpContext.Session.GetString("Usuario");
            ViewBag.Tipo = HttpContext.Session.GetInt32("Tipo");
            if (id != membresium.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(membresium);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembresiumExists(membresium.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteCedula"] = new SelectList(_context.Clientes, "ClienteCedula", "ClienteCedula", membresium.ClienteCedula);
            return View(membresium);
        }

        // GET: Membresia/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Membresia == null)
            {
                return NotFound();
            }

            var membresium = await _context.Membresia
                .Include(m => m.ClienteCedulaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (membresium == null)
            {
                return NotFound();
            }

            return View(membresium);
        }

        // POST: Membresia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Membresia == null)
            {
                return Problem("Entity set 'Gym_BDContext.Membresia'  is null.");
            }
            var membresium = await _context.Membresia.FindAsync(id);
            if (membresium != null)
            {
                _context.Membresia.Remove(membresium);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembresiumExists(int id)
        {
          return (_context.Membresia?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SistemaGestionGimnasio/Views/Membresia/Create.cshtml
@model SistemaGestionGimnasio.Models.Membresium

@{
    ViewData["Title"] = "Create";
}
@if (ViewBag.Tipo == 1)
{
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}
else
{
    Layout = "~/Views/Shared/_LayoutEmpleado.cshtml";
}


<h1>Registrar Membresia</h1>

<h4>Membresium</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input type="date" asp-for="FechaInicio" class="form-control" id="fechaInicio" onchange="calcularFechaVencimiento()" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaVencimiento" class="control-label"></label>
                <input type="date" asp-for="FechaVencimiento" class="form-control" id="fechaVencimiento" />
                <span asp-validation-for="FechaVencimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoMembresia" class="control-label">Tipo de Membresia</label>
                <input asp-for="TipoMembresia" class="form-control" />
                <span asp-validation-for="TipoMembresia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClienteCedula" class="control-label">Cedula del cliente</label>
                <select asp-for="ClienteCedula" class ="form-control" asp-items="ViewBag.ClienteCedula"></select>
            </div>
            <div class="form-group my-2">
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

<script>
    function calcularFechaVencimiento() {
        var fechaInicio = document.getElementById("fechaInicio").value;
        var fechaInicioDate = new Date(fechaInicio);

        // Añadir un mes a la fecha de inicio
        fechaInicioDate.setMonth(fechaInicioDate.getMonth() + 1);

        // Asignar la fecha calculada al campo de fecha de vencimiento
        document.getElementById("fechaVencimiento").value = fechaInicioDate.toISOString().split('T')[0];
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaGestionGimnasio/Views/Membresia/Delete.cshtml
@model SistemaGestionGimnasio.Models.Membresium

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Membresium</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaVencimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoMembresia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoMembresia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClienteCedulaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClienteCedulaNavigation.ClienteCedula)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SistemaGestionGimnasio/Views/Membresia/Details.cshtml
@model SistemaGestionGimnasio.Models.Membresium

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Membresium</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaVencimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoMembresia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoMembresia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClienteCedulaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClienteCedulaNavigation.ClienteCedula)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SistemaGestionGimnasio/Views/Membresia/Edit.cshtml
@model SistemaGestionGimnasio.Models.Membresium

@{
    ViewData["Title"] = "Edit";
}
@if (ViewBag.Tipo == 1)
{
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}
else
{
    Layout = "~/Views/Shared/_LayoutEmpleado.cshtml";
}
<h1>Modificar membresia</h1>

<h4>Membresia</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input type="date" asp-for="FechaInicio" class="form-control" id="fechaInicio" onchange="calcularFechaVencimiento()" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaVencimiento" class="control-label"></label>
                <input type="date" asp-for="FechaVencimiento" class="form-control" id="fechaVencimiento" />
                <span asp-validation-for="FechaVencimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoMembresia" class="control-label">Tipo de Membresia</label>
                <input asp-for="TipoMembresia" class="form-control" />
                <span asp-validation-for="TipoMembresia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClienteCedula" class="control-label">Cedula del cliente</label>
                <select asp-for="ClienteCedula" class="form-control" asp-items="ViewBag.ClienteCedula"></select>
            </div>
            <div class="form-group my-2">
                <input type="submit" value="Guardar cambios" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaGestionGimnasio/Views/Membresia/Index.cshtml
@model IEnumerable<SistemaGestionGimnasio.Models.Membresium>

@{
    ViewData["Title"] = "Index";
}
@if (ViewBag.Tipo == 1)
{
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}
else
{
    Layout = "~/Views/Shared/_LayoutEmpleado.cshtml";
}

<h1>Gestión de Membresías</h1>
<p>
    <a asp-action="Create">Agregar Membresía</a>
</p>

@ViewBag.ErrorEliminar

@using (Html.BeginForm("Index", "Membresia", FormMethod.Get))
{
    <p>
        Filtrar por Cédula: <input type="text" name="filtroCedula" />
        Fecha de Inicio: <input type="date" name="filtroFechaInicio" />
        Fecha de Vencimiento: <input type="date" name="filtroFechaFin" />
        <input type="submit" value="Filtrar" class="btn btn-secondary" />
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                Fecha de Inicio
            </th>
            <th>
                Fecha de Vencimiento
            </th>
            <th>
               Tipo Membresia
            </th>
            <th>
                Monto
            </th>
            <th>
                Cédula Cliente
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaVencimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoMembresia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClienteCedulaNavigation.ClienteCedula)
            </td>
            <td>
                 <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Modificar</a>
            </td>
        </tr>
}
    </tbody>
</table>